### ISSUE TITLE
申请适配vercel.com

### ISSUE THREAD

**Issue by Raudience** [hx-w/qndxx#10]
netlify的界面太不人性化了，而且主域名在国内还被墙了，而vercel.com可以正常访问

**Comment by hx-w** [comment]
#11 已适配，不过国内貌似要梯子才能打开。

**Comment by haha44444** [comment]
> #11 已适配，不过国内貌似要梯子才能打开。

坐标辽宁，运营商电信，已确认vercel.app被墙👀

**Comment by Raudience** [comment]
但是github readme界面里的vercel部署链接只是一张图片

**Comment by Raudience** [comment]
com还能访问，这样有自己的域名就能不挂梯子进行部署和访问，但netlify好像部署都要挂梯子
