### ISSUE TITLE
readme界面里的vercel部署链接只是一张图片

### ISSUE THREAD

**Issue by Raudience** [hx-w/qndxx#12]
github readme界面里的vercel部署链接只是一张图片(❁´◡`❁)

**Comment by hx-w** [comment]
我印象里vercel有提供status badge，但是没找到。readme里的badge是找的第三方库提供的，现在已经重定向到vercel project页。

**Comment by Raudience** [comment]
您要把它上传成一个vercel中的公共项目，我们才能直接部署
![image](https://github.com/hx-w/qndxx/assets/52769726/c43bdbe5-f333-4b1e-a193-9dfc1db752a3)

**Comment by hx-w** [comment]
在readme里加了一键部署的按钮，开头的badge仅用来看状态吧。

**Comment by Raudience** [comment]
好的
