### ISSUE TITLE
页面空白

### ISSUE THREAD

**Issue by NianBroken** [hx-w/qndxx#13]
标题显示”正在请求数据...“、页面空白

**Comment by haha44444** [comment]
![image](https://github.com/hx-w/qndxx/assets/60396495/bc8d4bf3-73a3-4b0f-b6e6-760f316b3a6c)
应该是华为云那边的问题，我换了两个华为云账号都登不上

**Comment by NianBroken** [comment]
> ![image](https://user-images.githubusercontent.com/60396495/261550892-bc8d4bf3-73a3-4b0f-b6e6-760f316b3a6c.png) 应该是华为云那边的问题，我换了两个华为云账号都登不上

四个链接均空白

**Comment by haha44444** [comment]
> > ![image](https://user-images.githubusercontent.com/60396495/261550892-bc8d4bf3-73a3-4b0f-b6e6-760f316b3a6c.png) 应该是华为云那边的问题，我换了两个华为云账号都登不上
> 
> 四个链接均空白

是的，四个链接均使用我的华为云云函数，云函数在我本机已经跑了一遍了，没有问题，目测可能是华为云那边出问题了，账号都登不上
![image](https://github.com/hx-w/qndxx/assets/60396495/e4e8e05b-1fbe-4678-816f-6b29bba67759)

**Comment by NianBroken** [comment]
> > > ![image](https://user-images.githubusercontent.com/60396495/261550892-bc8d4bf3-73a3-4b0f-b6e6-760f316b3a6c.png) 应该是华为云那边的问题，我换了两个华为云账号都登不上
> > 
> > 
> > 四个链接均空白
> 
> 是的，四个链接均使用我的华为云云函数，云函数在我本机已经跑了一遍了，没有问题，目测可能是华为云那边出问题了，账号都登不上

那如果我自行部署，调用的是我这边的服务，还是你的云函数？

**Comment by haha44444** [comment]
> > > > ![image](https://user-images.githubusercontent.com/60396495/261550892-bc8d4bf3-73a3-4b0f-b6e6-760f316b3a6c.png) 应该是华为云那边的问题，我换了两个华为云账号都登不上
> > > 
> > > 
> > > 四个链接均空白
> > 
> > 
> > 是的，四个链接均使用我的华为云云函数，云函数在我本机已经跑了一遍了，没有问题，目测可能是华为云那边出问题了，账号都登不上
> 
> 那如果我自行部署，调用的是我这边的服务，还是你的云函数？

更改一下src/App.vue就行
![image](https://github.com/hx-w/qndxx/assets/60396495/998dfd32-b9f1-4f29-b48f-3f2106347410)

**Comment by NianBroken** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/60396495/261550892-bc8d4bf3-73a3-4b0f-b6e6-760f316b3a6c.png) 应该是华为云那边的问题，我换了两个华为云账号都登不上
> > > > 
> > > > 
> > > > 四个链接均空白
> > > 
> > > 
> > > 是的，四个链接均使用我的华为云云函数，云函数在我本机已经跑了一遍了，没有问题，目测可能是华为云那边出问题了，账号都登不上
> > 
> > 
> > 那如果我自行部署，调用的是我这边的服务，还是你的云函数？
> 
> 更改一下src/App.vue就行 ![image](https://user-images.githubusercontent.com/60396495/261552890-998dfd32-b9f1-4f29-b48f-3f2106347410.png)

就是说如果我自行部署，也需要使用到云函数，对吗？
有没有可以使用服务器运行的方法？

**Comment by haha44444** [comment]
> 

应该暂时没有

**Comment by haha44444** [comment]
> > > > > > ![image](https://user-images.githubusercontent.com/60396495/261550892-bc8d4bf3-73a3-4b0f-b6e6-760f316b3a6c.png) 应该是华为云那边的问题，我换了两个华为云账号都登不上
> > > > > 
> > > > > 
> > > > > 四个链接均空白
> > > > 
> > > > 
> > > > 是的，四个链接均使用我的华为云云函数，云函数在我本机已经跑了一遍了，没有问题，目测可能是华为云那边出问题了，账号都登不上
> > > 
> > > 
> > > 那如果我自行部署，调用的是我这边的服务，还是你的云函数？
> > 
> > 
> > 更改一下src/App.vue就行 ![image](https://user-images.githubusercontent.com/60396495/261552890-998dfd32-b9f1-4f29-b48f-3f2106347410.png)
> 
> 就是说如果我自行部署，也需要使用到云函数，对吗？ 有没有可以使用服务器运行的方法？

你指的是这个云函数用服务器运行？

**Comment by hx-w** [comment]
改用netlify云函数的方法，整个部署流程不再需要外接付费/第三方服务。
但是由于h5.cyol.com域名屏蔽了境外ip，暂时没想到怎么获取最新一期的名称（用于显示网站title），
所以暂时需要手动用?id=xxx的形式将最新一期的名称写在url里，例如：
**https://qndxx.scubot.com?id=2023年第18期**

这个方式不太友好，等有更好的想法再改了。

**Comment by hx-w** [comment]
![](https://imgbed.scubot.com/image/c1b95e78c6dd48fd53abcd245360f691.jpg)

加了一个框，用于输入标题。
